version: '3.8'

services:
    omniroute:
        image: "diegosouzapw/omniroute:latest"
        container_name: omniroute
        restart: unless-stopped
        stop_grace_period: "40s"
        networks:
            - "${DOCKER_NETWORK}"
        volumes:
            - "omniroute-data:/app/data"
        ports:
            - "${TRAEFIK_PORT:-20128}:${PORT:-20128}"
        env_file:
            - .env
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${DOCKER_NETWORK}"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.rule=Host(`${TRAEFIK_SERVICE_NAME}.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.entrypoints=web"
            - "traefik.http.services.${TRAEFIK_SERVICE_NAME}.loadbalancer.server.port=${TRAEFIK_PORT:-20128}"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

volumes:
    omniroute-data:

networks:
    docker_lan_network:
        external: true
