version: '3.8'

services:
    it-tools:
        image: corentinth/it-tools:latest
        container_name: it-tools
        restart: unless-stopped
        networks:
            - "${DOCKER_NETWORK}"
        environment:
            - TZ=Europe/Berlin
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${DOCKER_NETWORK}"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.rule=Host(`${TRAEFIK_SERVICE_NAME}.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.entrypoints=web"
            - "traefik.http.services.${TRAEFIK_SERVICE_NAME}.loadbalancer.server.port=${TRAEFIK_PORT:-80}"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

networks:
    docker_lan_network:
        external: true
