version: '3.8'

services:
    dozzle:
        image: amir20/dozzle:latest
        container_name: dozzle
        restart: unless-stopped
        networks:
            - "${DOCKER_NETWORK}"
        environment:
            - TZ=Europe/Berlin
            - DOZZLE_AUTH_PROVIDER=simple
            - DOZZLE_NO_ANALYTICS=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data:/data
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${DOCKER_NETWORK}"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.rule=Host(`${TRAEFIK_SERVICE_NAME}.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.entrypoints=web"
            - "traefik.http.services.${TRAEFIK_SERVICE_NAME}.loadbalancer.server.port=${TRAEFIK_PORT:-8080}"
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "2"
        healthcheck:
            test: ["CMD", "/dozzle", "healthcheck"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s

networks:
    docker_lan_network:
        external: true

