services:
    roundcube:
        container_name: roundcube
        image: roundcube/roundcubemail:latest
        restart: always
        environment:
            - "ROUNDCUBEMAIL_DEFAULT_HOST=${ROUNDCUBEMAIL_DEFAULT_HOST}"
            - "ROUNDCUBEMAIL_SMTP_SERVER=${ROUNDCUBEMAIL_SMTP_SERVER}"
            - "ROUNDCUBEMAIL_SMTP_PORT=${ROUNDCUBEMAIL_SMTP_PORT}"
            - "ROUNDCUBEMAIL_IMAP_PORT=${ROUNDCUBEMAIL_IMAP_PORT}"
            - "ROUNDCUBEMAIL_PLUGINS=alias_auth"
            - "ROUNDCUBEMAIL_DB_TYPE=${ROUNDCUBEMAIL_DB_TYPE}"
            - "ROUNDCUBEMAIL_DB_HOST=${ROUNDCUBEMAIL_DB_HOST}"
            - "ROUNDCUBEMAIL_DB_USER=${ROUNDCUBEMAIL_DB_USER}"
            - "ROUNDCUBEMAIL_DB_PASSWORD=${ROUNDCUBEMAIL_DB_PASSWORD}"
            - "ROUNDCUBEMAIL_DB_NAME=${ROUNDCUBEMAIL_DB_NAME}"
        depends_on:
            - roundcube-db
        volumes:
            - roundcube_data:/var/www/html
            - ./roundcube/plugins/alias_auth:/var/www/html/plugins/alias_auth:ro
            - ./secrets:/run/secrets:ro
        networks:
            - docker_lan_network
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=docker_lan_network"
            - "traefik.http.routers.roundcube.rule=Host(`mail.docker.lan`)"
            - "traefik.http.routers.roundcube.entrypoints=web"
            - "traefik.http.services.roundcube.loadbalancer.server.port=80"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    roundcube-db:
        image: mariadb:latest
        container_name: roundcube-db
        restart: always
        environment:
            - "MYSQL_DATABASE=${ROUNDCUBEMAIL_DB_NAME}"
            - "MYSQL_USER=${ROUNDCUBEMAIL_DB_USER}"
            - "MYSQL_PASSWORD=${ROUNDCUBEMAIL_DB_PASSWORD}"
            - "MYSQL_ROOT_PASSWORD=${ROUNDCUBEMAIL_DB_ROOT_PASSWORD}"
        volumes:
            - roundcube_db_data:/var/lib/mysql
        networks:
            - docker_lan_network
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

volumes:
    roundcube_data:
    roundcube_db_data:

networks:
    docker_lan_network:
        external: true
