# https://github.com/nicolargo/glances

services:
    glances:
        image: nicolargo/glances:latest
        environment:
            - TZ=Europe/Berlin
            - PGID=1000
            - PUID=1000
            - GLANCES_OPT=-w
        privileged: true
        pid: host
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        restart: unless-stopped
        container_name: glances
        networks:
            - "${DOCKER_NETWORK}"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${DOCKER_NETWORK}"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.rule=Host(`${TRAEFIK_SERVICE_NAME}.${TRAEFIK_DOMAIN}`)"
            - "traefik.http.routers.${TRAEFIK_SERVICE_NAME}.entrypoints=web"
            - "traefik.http.services.${TRAEFIK_SERVICE_NAME}.loadbalancer.server.port=${TRAEFIK_PORT:-61208}"

networks:
    docker_lan_network:
        external: true
